// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slrnlaoxwtlbtjudsyft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNscm5sYW94d3RsYnRqdWRzeWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjQxOTQsImV4cCI6MjA2NDY0MDE5NH0.XEf9Z-wSSaXEmQLqHp5gJQXlEVoqm-OzTqjZZDOHpxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);